name: markdown_editor_advanced
description: A TextField Widget that allow you to convert easily what's in the
  TextField to Markdown with custom toolbar support.

version: 1.0.0

homepage: https://github.com/EmilyMoonstone/markdown_editor_advanced
repository: https://github.com/EmilyMoonstone/markdown_editor_advanced

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1
  markdown: ^7.3.0
  flutter_markdown: ^0.7.7+1
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: null
